from .api import (
    DEFAULT_CONTAINERS_PATH,
    DEFAULT_CVMFS_MIRROR,
    DEFAULT_CVMFS_MIRRORS,
    DEFAULT_CVMFS_REPO,
    NeurodeskContainer,
    SharedDirectory,
    SharedPath,
    connect,
    container,
    load_deploy_metadata,
    resolve_base_url,
    resolve_container_reference,
    search,
    share_dir,
)
from .client import PyNeurodeskClient
from .models import (
    CommandResult,
    CVMFSDirectoryEntry,
    CVMFSListResponse,
    CVMFSReadRequest,
    CVMFSReadResponse,
    CVMFSSource,
    ContainerReference,
    DaemonState,
    DeployMetadata,
    EmulatorState,
    ImageMetadataState,
    ImageSource,
    ImageState,
    ImportImageRequest,
    KernelState,
    NetworkConfig,
    PortForward,
    RunCommandRequest,
    ShareMount,
    VMSupportedState,
)
from .shell import main as shell_main

__all__ = [
    "CommandResult",
    "CVMFSDirectoryEntry",
    "CVMFSListResponse",
    "CVMFSReadRequest",
    "CVMFSReadResponse",
    "CVMFSSource",
    "ContainerReference",
    "DEFAULT_CONTAINERS_PATH",
    "DEFAULT_CVMFS_MIRROR",
    "DEFAULT_CVMFS_MIRRORS",
    "DEFAULT_CVMFS_REPO",
    "DaemonState",
    "DeployMetadata",
    "EmulatorState",
    "ImageSource",
    "ImageMetadataState",
    "ImageState",
    "ImportImageRequest",
    "KernelState",
    "NetworkConfig",
    "NeurodeskContainer",
    "PortForward",
    "PyNeurodeskClient",
    "RunCommandRequest",
    "ShareMount",
    "SharedDirectory",
    "SharedPath",
    "VMSupportedState",
    "connect",
    "container",
    "load_deploy_metadata",
    "main",
    "resolve_base_url",
    "resolve_container_reference",
    "search",
    "share_dir",
]


def main() -> None:
    raise SystemExit(shell_main())
